title: CodeOnDisc
email: admin@compaqdisc.com
author: CompaqDisc
description: >- # this means to ignore newlines until "baseurl:"
  Awesome on a CD-R!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.compaqdisc.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CompaqDisc
github_username:  CompaqDisc
google_analytics: UA-109309717-1

include: ['+compaqdisc']

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
plugins:
  - jekyll-feed
